### ISSUE TITLE
Getting 400 error on Slack Integrations

### ISSUE THREAD

**Issue by anshsrtv** [flowwer-dev/pull-request-stats#32]
I am receiving this error while trying to run the actions in one of my org's private repo. 
```
Error: Request failed with status code 400
```
Our team Fyle has sponsored the project thinking it might add value but it keeps giving a 400 bad request whenever run. Attaching a screenshot of the logs here.

![Screenshot 2022-05-19 at 5 41 31 PM](https://user-images.githubusercontent.com/49693160/169290360-201e9562-a464-4b52-b8bc-9898e68fa915.png)
 
Let me know if there are any permissions that need to be enabled for sending the message to slack.

**Comment by manuelmhtr** [comment]
Hi @anshsrtv,
First, thank you very much for your support. You are my very first sponsor and that makes your company special to me. I'll work hard to make it worth 💪 

Sorry about this problem. I've sent a new version (`v2.3.1`) adding logs to debug the Slack integration. In order to fix it, could you help me with:

1. Making sure you are running the action from `master`, `v2` or `v2.3.1` (this will make logs available).
2. Adding the variable `ACTIONS_STEP_DEBUG` with value `true` to your repository secrets (in the repo you are running the action). This will [enable debug logs](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md).
3. Sending those logs to me (email: m@nuel.mx). I'm particularly interested in the log that starts with `Post a Slack message with params:` and the one with `Error posting Slack message:`.

That would help me a lot to fix this for you. Thank you!

**Comment by anshsrtv** [comment]
Hey, I tried to debug this and found that the data for 30 days was too big for a single message in slack, so I reduced it to 15 days. Can we get the table format in slack as in the github PR description?

**Comment by manuelmhtr** [comment]
Thanks for the update @anshsrtv, I'll add this to the "troubleshooting" section.

---

> I reduced it to 15 days

As an alternative, if you need the stats for the lasts 30 or more days, you could use the `limit` option. This way the stats still calculated for the desired time frame but the message is limited to the first X rows to fit the Slack limitation.

---

> Can we get the table format in slack as in the github PR description?

Unfortunately Slack blocks [does not support tables](https://stackoverflow.com/a/55817539/1628009) yet. That's a huge limitation to make it looks the same than Github. The only option would post them as an image, but it would loose more important capabilities like copying text, and using links.

However, Slack still improving their [Blocks API](https://api.slack.com/reference/block-kit/blocks), I hope anytime soon they support tables and I could migrate to that format then.

**Comment by anshsrtv** [comment]
Hi @manuelmhtr, Can we edit the slack message we send? I mean can we add the repo name to the slack message?

**Comment by manuelmhtr** [comment]
@anshsrtv sorry for the late reply.
1. Review time is calculated as the moment of the first review minus the most recent date between the last commit and the time the PR was published. You can check it [here](https://github.com/flowwer-dev/pull-request-stats/blob/master/src/parsers/parseReview.js). The logic behind this is, somebody might publish the PR first but keep adding commits before requesting for reviews.

2. Sounds like a good idea. I'll make some time to launch this feature this week ;)

**Comment by manuelmhtr** [comment]
Hi @anshsrtv I just released [v2.4.1](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.4.1) which now prints the repos or organizations related to the stats.
