### ISSUE TITLE
Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by famin3** [flowwer-dev/pull-request-stats#37]
Started happening Monday afternoon, what I've found :
- renamed token to github-token
![image](https://user-images.githubusercontent.com/17994514/174825919-c21ad583-6ab0-492c-acca-dac6a783cd14.png)

Possible changes that caused it are in commit
https://github.com/flowwer-dev/pull-request-stats/commit/507103c1f4e76ef5047b92cc738e40637b37bdde

**Comment by manuelmhtr** [comment]
Hi @famin3, thanks for reporting this problem. I missed a condition that was making `token` parameter to be empty (the new parameter `github-token` is ok and there's no need to assign a value, the action needs the default value).

The problem is fixed in [v2.4.2](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.4.2), could you run it again and confirm if that works?

**Comment by famin3** [comment]
@manuelmhtr all seems to work again. Thanks for quick response!
