### ISSUE TITLE
Feature: Number of Reviews Requested of user

### ISSUE THREAD

**Issue by thejuan** [flowwer-dev/pull-request-stats#42]
It'd be interesting to see the number of times a reviewer has been requested to review next to the total reviews.
The time to review can be artificially low if they don't respond to many requests

**Comment by manuelmhtr** [comment]
Hi @thejuan, that's true!

I might do it in 2 stages:
1. When a reviewer is assigned but didn't respond, count the time since they were requested to the time the PR was closed as reviewing time; but don't count that PR as a review. That way only time will be impacted.
2. I'm not sure if the times a reviewer has been requested is a very meaningful metric alone, but many people are requesting for some other stats, so I'm may add them and let people choose which stats to be displayed.
