### ISSUE TITLE
Android Lint Reporter got undefined

### ISSUE THREAD

**Issue by seabornlee** [flowwer-dev/pull-request-stats#46]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/735708/184585440-18123966-e721-40e7-b45a-849e1555ad62.png">

We use https://github.com/worker8/AndroidLintReporter to comment lint reports on PR automatically, but it shows undefined as username (the second one in the above image).

Can I define the name or exclude the reporter?

**Comment by manuelmhtr** [comment]
Hi @seabornlee, thanks for sharing this issue.

I made an improvement on [v2.4.4](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.4.4) to filter reviewers with undefined username. This should remove the empty row caused by `AndroidLintReporter`.

Could you give it a try and confirm if it works for you?

Thanks

**Comment by seabornlee** [comment]
It works now. Thanks very much!
