### ISSUE TITLE
parseUser.js crashes with null author

### ISSUE THREAD

**Issue by derek-young** [flowwer-dev/pull-request-stats#5]
When a PR is created by a user who is subsequently removed from an organization, the `node.author` value is `null`, which is then passed into `parseUser.js` and throws an uncaught type error of "Cannot read property 'databaseId' of undefined". I can create a PR for this, but you'll have to let me know how you want this handled, i.e. do we ignore that PR or aggregate these under an "unknown" user?

**Comment by manuelmhtr** [comment]
Hi @derek-young, thanks for your support.
I think the best would be to ignore the user (since it was removed it should be important to keep tracking their stats).

I recently did a similar change to prevent checking bot reviews (https://github.com/flowwer-dev/pull-request-stats/commit/1bc765755df4fbc0a52bf761b4b3d97408b5b20b, `src/interactors/getReviewers/groupReviews.js`), it may help you.

**Comment by derek-young** [comment]
Doesn't look like I can link the issue, but a PR for this fix is up! https://github.com/flowwer-dev/pull-request-stats/pull/6 Thanks Manuel

**Comment by manuelmhtr** [comment]
Solution is ready on v2.0.2.
Thanks for contributing @derek-young
