### ISSUE TITLE
Slack integration not working

### ISSUE THREAD

**Issue by piersmacdonald** [flowwer-dev/pull-request-stats#52]
Here's the Github Action error

```
Error posting Slack message: Error: Request failed with status code 400
```

**Comment by manuelmhtr** [comment]
Hi, @piersmacdonald thanks for reporting the issue. This problem was reported before and resulted being the characters limit of Slack. It was supposed to be [fixed](https://github.com/flowwer-dev/pull-request-stats/commit/ac5c6eb7c6f48b0e12253dd6cd511a81fd088570), but maybe I made a mistake.

Could you try setting the `limit` option to 5 or so?

**Comment by manuelmhtr** [comment]
Hi @piersmacdonald happy to help you with the Slack integration :)
