### ISSUE TITLE
Local run

### ISSUE THREAD

**Issue by xild** [flowwer-dev/pull-request-stats#9]
Hi! Is there a way to use it locally without the GitHub actions? 

If so, I could submit a PR updating the readme with some instructions

**Comment by manuelmhtr** [comment]
Hi @xild,
Unfortunately is not possible at this point. In the future, I might separate the project into an npm dependency and the action (this project).

For now, you could fork it and pass the required parameters to the [execute function](https://github.com/flowwer-dev/pull-request-stats/blob/master/src/execute.js), you'll also need to return or print `content` rather than calling `postComment`.

Finally, it could be great if you could share what's you use case for running locally?
