### ISSUE TITLE
doc: Total comments

### ISSUE THREAD

**Issue by rowi1de** [flowwer-dev/pull-request-stats#98]
Could you clarify which comments count towards the following:
- Total comments: The count of all the comments while reviewing other users' Pull Requests in the period (comments in own PRs don't count).
- Does an approval or request change or a normal comment on a PR Count? Or is it just comments on Code / Changed files

**Comment by manuelmhtr** [comment]
Hello @rowi1de, great question. I've updated the documentation as follows:

> * **Total comments:** The number of comments made while reviewing other users' Pull Requests during the specified period. Comments made on your own PRs or general PR discussions are excluded; only comments directly related to code are counted.

At the moment, only code-related comments are included (ALL of them, since any normal comment on code generates a review). However, I realize that general comments in reviews are also important (those when submitting a review). I plan to include them in the statistics in a future update.

**Comment by rowi1de** [comment]
Hey @manuelmhtr I would say this should be an option to enable.
For code comments it is more clear that it is relevant.
For the general comment it could also just be LGTM.

**Comment by manuelmhtr** [comment]
Hello @rowi1de
Now the general comments on the reviews are counted, since they can be as important as the other code comments.

Latter I'll add a metric to differentiate the "LGTM" comment vs the relevant ones.
